### ISSUE TITLE
A way to tell Zinc that a cloned repository doesn't have to be synced on iCloud

### ISSUE THREAD

**Issue by JaviSoto** [mindsnacks/Zinc-ObjC#7]

**Comment by amrox** [comment]
I thought it already did this. If not it just need to add the com.apple.mobilebackup thing 

## 

Andy Mroczkowski
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by JaviSoto** [comment]
Actually I just created this as a reminder for me to check if this was already being done. I just checked, and yea, Zinc is marking all extracted files as non backupable.
